### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by stevepeak**
Please do not merge. Checking file structure to see whats going on.

There should be a `.coverage` file that is created by `coveragepy`.

### CODE REVIEW

**Comment by stevepeak** [comment]
This line here is an issue: https://travis-ci.org/par2/lamana/jobs/109525839#L585

However I see the `.coverage` file here: https://travis-ci.org/par2/lamana/jobs/109525839#L565

**Comment by par2** [comment]
You know, locally, these commands also do not generate a report, but if i add the `combine` command, then it works.

```
nosetests --with-cov --cov lamana
coverage combine
coverage xml
```

Not sure if this is necessary to generate the reports...

**Comment by stevepeak** [comment]
Hum.. I had through coveragepy could detect the "not combined" files.

**Comment by stevepeak** [comment]
Bingo :+1:

**Comment by par2** [comment]
Many thanks.  Finally, once I have the the coverage extensions installed,
how do I get it working on my repo?  Thanks again.

**Comment by stevepeak** [comment]
The extension should work immediately. Do you see Codecov working on this file: https://github.com/par2/lamana/blob/develop/lamana/constructs.py

Thank you :)

**Comment by par2** [comment]
It works now.  Yesterday it was saying No Coverage, despite codecov having
a report.
Thanks.

**Pull request merged**
